### ISSUE TITLE
Expand unit test coverage

### ISSUE THREAD

**Issue by kneitinger** [kneitinger/nightgraph#17]
## Goal
At least 80% test coverage in repo.

## Tasks
- [ ] `nightsketch_derive` macro internals
- [x] #19
- [ ] `nightsketch` features (testing clap derivations, etc)
- [ ] `nightgraphics` geometry/canvas/render coverage improvement
- [ ] `nightgraph-ui` custom components (sketch loading, parameter control generation, etc)

## Note
I don't believe sketches themselves make sense to include in this figure
