### ISSUE TITLE
Boolean geometric operations

### ISSUE THREAD

**Issue by kneitinger** [kneitinger/nightgraph#5]
Currently `nightgraphics`' `Shaped` triat has a `difference` operation.  In addition to that it should have `union` and `intersection`.

### Tasks

- [ ] Add `union` operation to `Shaped` trait
- [ ] Add `intersection` operation to `Shaped` trait (this very well might share a lot of code with `difference`)
- [ ] Consider returning a `Result` as some operations do not make sense.  For example, what does a the difference of 2 non-closed shapes imply?  What about the union of a circle and a line?
