### ISSUE TITLE
Populate READMEs

### ISSUE THREAD

**Issue by kneitinger** [kneitinger/nightgraph#7]
## Overview
All crates should have thorough READMEs that explain their purpose, how they're used, and if applicable technical details

## Tasks

- [ ] `nightsketch_derive`: should explain all of the code that `#[sketch]` generates, and the attributes/options
- [ ] `nightsketch`: should explain how to add a sketch
- [ ] `nightgraphics`: as the most potentially externally useful crate, it should explain an overview of features, some example snippets, some design philosophy, etc.
- [ ] `nightgraph-{ui,cli}`: build instructions (including wasm), screenshots, usage, feature list
